### PR TITLE
Allow callback for l_bfgs_b. Allow kwargs to optimization functions.

### PR DESCRIPTION
**Pull request by jseabold**
If you decide to bumpy minimum scipy version, might even be worth using the new minimize API. We haven't done it in statsmodels yet though FWIW.

### CODE REVIEW

**Comment by jseabold** [comment]
It also looks like `l_bfgs_b` displays the convergence information in a different way than the other optimizers. I can't recall exactly the details here, but it says it prints to stdout. At least in the notebook, I don't see anything, indicating whether or not the function converged. Might be worth catching this info and attaching to returned results? We're attaching all info returned from the optimizer if asked for.

**Comment by twiecki** [comment]
Looks good to me :+1:. Ultimately should probably refactor this to use `minimize` which takes a string argument of which minimze function to use like we do here. I think upgrading the scipy requirement is no big deal so my perspective is to scratch the backwards compat here.

**Comment by jseabold** [comment]
We recently only bumped up to scipy 0.9.0, though I don't recall the argument why other than the usual inertia. 0.12.0 came out 18 months ago. Your call.

**Comment by twiecki** [comment]
With 'we' you mean `statsmodels`?

**Comment by jseabold** [comment]
Yeah

**Comment by twiecki** [comment]
I think `pymc` users are generally more up-to-date but not sure what I base this on. I'll defer to @fonnesbeck.

**Comment by fonnesbeck** [comment]
I'm fine with this.

**Pull request merged**
