### PR TITLE
Fix asarray typo

### PR DESCRIPTION
**Pull request by jseabold**
There was a typo in my last fix for the asarray bug in pymc/distributions.py. This commit fixes the typo.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
These already seem to be in master.

**Comment by jseabold** [comment]
I thought I was using a clean clone of master when I noticed the typo. Am I looking in the wrong place? This is np.asrry not np.asarray?

https://github.com/pymc-devs/pymc/blob/master/pymc/distributions.py#L1188

**Comment by jseabold** [comment]
I am lost with git. Still trying to switch over. Not sure where I went wrong yet, but this is the commit I want

https://github.com/jseabold/pymc/commit/7c23fabc7253758099967fac75a668ac447d1cd3

**Comment by fonnesbeck** [comment]
Ah, right. Sorry, I missed that. I fixed it in 97208406323c0c4614cb768c4f0e395c297e469f

Thanks,
cf

**Pull request closed without merging**
