### PR TITLE
DOC: Added build status icon to readme.md.

### PR DESCRIPTION
**Pull request by twiecki**
Forgot this little tweak.

### CODE REVIEW

**Comment by jsalvatier** [comment]
Failed with: 

# 

## ERROR: tests.test_examples.test_examples('/home/travis/build/twiecki/pymc/pymc/../examples/regression_patsy.py',)

Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/twiecki/pymc/tests/test_examples.py", line 35, in check_example
    imp.load_source('**main**', path.basename(p))
  File "regression_patsy.py", line 4, in <module>
    import patsy
ImportError: No module named patsy

**Comment by twiecki** [comment]
Great example of why this is useful ;).

Shouldn't have pushed the example to the same branch. You could just add:

```
[![Build Status](https://travis-ci.org/pymc-devs/pymc.png)](https://travis-ci.org/pymc-devs/pymc)
```

To the readme and register at travis.

**Comment by twiecki** [comment]
If you want to include the patsy example it builds now fine after adding the patsy dependency.

**Comment by jsalvatier** [comment]
Can we do the patsy example as a separate pull? I want to include the first bit, but I think the example think needs some more explanation about what patsy is and how it's being used.

**Comment by twiecki** [comment]
OK, removed the patsy example from this PR.

**Comment by jsalvatier** [comment]
Thanks!

**Pull request merged**
