### PR TITLE
Text and SQLite backends (update)

### PR DESCRIPTION
**Pull request by kyleam**
This PR is an update of #500.

The only new change to the interface is a function to dump a trace sampled with the NDArray backend into a text database. Most other changes are focused on updating the testing approach.

### CODE REVIEW

**Comment by kyleam** [comment]
Looks like a few tests fail with python 2 (I only tested it locally with python 3). I'll push a fix soon.

**Comment by kyleam** [comment]
The error above is from the py2.7 distributions tests stalling.

**Comment by twiecki** [comment]
Normally you can just restart it and it'll pass. But this has been in the works for a while so I'm sure it's solid and good to merge!

**Comment by kyleam** [comment]
Nice, I didn't realize I could do that. Thanks

**Comment by twiecki** [comment]
@jsalvatier You looked at this most. Ready to merge?

**Comment by jsalvatier** [comment]
Let me try to read and understand the tests by next weekend and then we'll
merge. If I don't by Sunday, lets merge anyway.

**Comment by twiecki** [comment]
OK, I'll merge this since it's been a month. Looks great, thanks for all the hard work @kyleam

**Comment by mrocklin** [comment]
I'd like to better understand how/why PyMC uses different backends.  Is there documentation on this somewhere?

**Comment by mrocklin** [comment]
Oh, and people should tweet interesting PRs more often.

**Comment by kyleam** [comment]
At this point, [backends/__init__.py](https://github.com/pymc-devs/pymc/blob/master/pymc/backends/__init__.py) contains the most documentation.

**Pull request merged**
