### PR TITLE
Better distribution creation syntax

### PR DESCRIPTION
**Pull request by jsalvatier**
For building a distribution you do `Normal.dist(mu, sd)` instead of `Normal(mu, sd)`. Random variables are still constructed by `Normal('x', mu, sd)`

Perhaps not ready for production.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
So, can I not create a distribution and evaluate its log-probability for arbitrary inputs? This is somewhat related to #264. I tried doing the usual evaluation using the Theano tensor function syntax, but this did not seem to work. I don't have to jump through all the bijection hoops to do this, do I?

**Comment by jsalvatier** [comment]
Right now, not on this branch, you should be able to do:

```
from pymc import * 
from theano.tensor import *
from theano import * 

theano.config.compute_test_value = 'ignore' 
mu = dvector('mu')
sd = dvector('sd')
x = dvector('x')

d = Normal(mu,sd)
f = function([mu,sd,x], d.logp(x))
f([0],[1],[.5])
```

I agree this is too complicated, and we should fix it, but I don't have good ideas yet.

**Comment by jsalvatier** [comment]
How about the following? 

```
from pymc import * 
from theano.tensor import *
from theano import *
def evallogp(dist): 
    def logp(value, *args, **kwargs):
        return dist.dist(*args, **kwargs).logp(value).tag.test_value
    return logp

logp = evallogp(Normal)
logp(0,1,.5)
```

**Comment by jsalvatier** [comment]
Or actually, you can do 

```
from pymc import * 
from theano.tensor import *
from theano import *

Normal.dist(0.,1.).logp(.5).tag.test_value
```

**Comment by fonnesbeck** [comment]
Can we combine the last two and have a convenience method that returns `tag.test_value`, so that we can do:

```
Normal.dist(0.,1.).logp(.5).eval()
```

or similar?

**Comment by jsalvatier** [comment]
That is in unfortunately out of our hands since it is purely a theano
variable.  We should talk to the theano list about the general election
issue of getting better debugging and this specific issue of better
evaluation. Would

**Comment by fonnesbeck** [comment]
It could be a function then, as you originally suggested.

**Comment by jsalvatier** [comment]
Yeah that works. We should talk to the theano in parallel

**Comment by fonnesbeck** [comment]
I take it we can close this one then?

**Pull request closed without merging**
