### PR TITLE
Slice sampler step function

### PR DESCRIPTION
**Pull request by fonnesbeck**
#217

### CODE REVIEW

**Comment by jsalvatier** [comment]
Looks good to me. 

Only thing this need is testing: you can see how I did it for the other samplers in https://github.com/pymc-devs/pymc/blob/pymc3/tests/test_step.py. (I think the tests need refactoring at some point, but they're good enough for now). 

Is SliceStep a better name than Slice? I'm ok either way.

**Comment by fonnesbeck** [comment]
I've added the slice sampler to test_step. I called the sampler Slice rather than SliceStep just to follow the convention of the other steps -- none of them use the 'Step' suffix.

**Comment by jsalvatier** [comment]
Looks good! Merging.

**Comment by jsalvatier** [comment]
should `track_progress` be `progressbar`? Seems more intuitive.

**Comment by fonnesbeck** [comment]
Sounds good to me.

**Pull request merged**
