### PR TITLE
Bumped six to version 1.5.2

### PR DESCRIPTION
**Pull request by twiecki**
The `six` that is bundled with `2.3` is quite outdated and caused some problems which were quite a headache to figure out where they were coming from (see https://github.com/ipython/ipython/issues/4784 and https://github.com/mwaskom/seaborn/issues/82). To save others the pain I updated `six.py` to `1.5.2` (most recent).

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Passes tests for me. I just fixed a Python 3 compatibility issue with setupegg.py before merging.

**Comment by fonnesbeck** [comment]
I wonder if I should just have six as a submodule.

**Comment by twiecki** [comment]
@fonnesbeck what do you mean? `pymc/six/six.py` instead of current `pymc/six.py`?

**Comment by fonnesbeck** [comment]
I just mean including it as a git submodule, so that changes in six are automatically included with PyMC 2.3.

**Comment by twiecki** [comment]
Btw. what's your take on pymc 2 bugfix releases?

**Comment by fonnesbeck** [comment]
My take is: I need to get 2.3.1 out soon. Folks are running into bugs on the 2.3 release pretty regularly.

**Comment by twiecki** [comment]
Oh, git submodule. Yeah, that makes sense. Could also be an external dependency but that might not be ideal.

**Comment by twiecki** [comment]
For `2.3.1` would be nice to figure out a `conda` recipe that works for osx and linux (windows one seems fine).

**Pull request merged**
