### PR TITLE
Change solve() to matrix_inverse().dot() in Wishart

### PR DESCRIPTION
**Pull request by jangevaare**
Avoids issues with missing grad() method in solve(), see https://github.com/pymc-devs/pymc/issues/350

### CODE REVIEW

**Comment by fonnesbeck** [comment]
This does seem to yield an error on Travis CI that I have not seen before. Does it pass your tests?    

```
======================================================================
ERROR: Test autocorrelation and autocovariance functions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pymc-devs/pymc/pymc/tests/test_stats.py", line 14, in test_autocorr
    assert_almost_equal(autocorr(y), 0.5, 2)
  File "/home/travis/build/pymc-devs/pymc/pymc/stats.py", line 46, in wrapped_f
    return f(pymc_obj, *args, **kwargs)
  File "/home/travis/build/pymc-devs/pymc/pymc/stats.py", line 59, in autocorr
    S = autocov(x, lag)
  File "/home/travis/build/pymc-devs/pymc/pymc/stats.py", line 46, in wrapped_f
    return f(pymc_obj, *args, **kwargs)
  File "/home/travis/build/pymc-devs/pymc/pymc/stats.py", line 74, in autocov
    return np.cov(x[:-lag], x[lag:], bias=1)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1816, in cov
    dtype = np.result_type(m, y, np.float64)
TypeError: data type not understood
```

**Comment by jangevaare** [comment]
Right now I am getting the same test results with both pymc-devs:pymc3 and jangevaa:pymc3. 

```
>>> from pymc import *
>>> test()
Running unit tests for pymc.tests
NumPy version 1.7.1
NumPy is installed in /Users/justin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy
Python version 2.7.3 | 64-bit | (default, Aug  8 2013, 05:37:06) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
nose version 1.3.0
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
<nose.result.TextTestResult run=1 errors=0 failures=0>
```

**Comment by jsalvatier** [comment]
Embarassingly, we don't have a test for Wishart. I'm working on fixing it though.

I think to run the tests you may have to use nosetests (just run `nosetests` in the parent directory).

**Comment by jangevaare** [comment]
Sorry, actual test results:

pymc-devs:pymc3

```
----------------------------------------------------------------------
Ran 92 tests in 135.289s

FAILED (errors=4)
<nose.result.TextTestResult run=92 errors=4 failures=0>
```

jangevaa:pymc3

```
----------------------------------------------------------------------
Ran 92 tests in 131.579s

FAILED (errors=4)
<nose.result.TextTestResult run=92 errors=4 failures=0>
```

All errors seem due to

```
ImportError: No module named examples
```

**Comment by twiecki** [comment]
Fixed in #390. Thanks for the PR!

**Pull request closed without merging**
