### PR TITLE
GLM

### PR DESCRIPTION
**Pull request by twiecki**
This is not ready for merging yet but I'm putting it up as WIP and to get some code review (continuation of #199). Once we finalize on the structure I'll add some tests. This branch is also based off of `scaling` which should be merged before this one.

I'm pretty happy with the interface now as it allows the creation of Bayesian GLMs with almost the same simplicity as in R or statsmodels. See http://nbviewer.ipython.org/urls/raw.github.com/pymc-devs/pymc/glm/pymc/examples/GLM.ipynb for examples.

Another thing that really helps is the initialization by fitting with `statsmodels` first and using this as a starting point.

Outstanding questions are:
1. Currently `statsmodels` is optional but is required for anything except `linear_component()`. I think this might be a reasonable trade-off. `statsmodels` itself is pretty light-weight.
2. I created a `glm` subdirectory. Is that where we want to keep this?
3. `links.py` and `families.py` ties together `theano` and `statsmodels`. We need to have 2 of everything so that we can initialize properly with the correct `statsmodel`. The individual classes make the code pretty modular and easy extendable. Not sure if someone has a better idea for how to structure these.
4. `glm`'s classes do not go into the `pymc` namespace but e.g. `pymc.glm.families` which I think is the right thing to do. To create a new glm, one would call `pymc.glm.glm()`. Not sure I like the `glm.glm` too much but I'm not sure what a better name for either the submodule or the function would be. Maybe it's fine though?

### CODE REVIEW

**Comment by fonnesbeck** [comment]
I'm a little confused by the examples in the notebook, mostly I think because there is so much going on automatically. So, a call to `glm` is creating nodes for the regression coefficients? I assume so because the contents of the model context is simply the specification of the start conditions and the step methods. It seems a little weird that the model specification is conflated with the specification of the starting conditions, given how models are typically built. Pretty slick though.

**Comment by fonnesbeck** [comment]
Also confused by the hierarchical GLM, where there is only one regressor prior but 4 regressors. Does it create 4 priors based on the single specification? This may be hiding too much.

**Comment by twiecki** [comment]
Yeah, the `glm` function is the fully automatic one. There's also `linear_component()` which only returns the matrix product (it does create distributions for the coefficients though). You can then use your own link function and pass that into the likelihood. I'll put up an example for that.

Currently you can supply the prior distribution to use for the intercept and (all) regressors. I agree that it should also be possible to pass in individual prior distribution for each regressor, that might make it more transparent.

Certainly it's divergent from the way models are normally specified where you always have to create each node individually. You can still do that of course but it all adds to the complexity. Plus the initialization is a little tricky.

**Comment by twiecki** [comment]
@fonnesbeck I added an example on how to use `linear_component()` and some more descriptions on how `glm()` is just syntactic sugar around it. 

I also changed the way priors can be defined. You can pass a dictionary now.

Let me know if this makes more sense.

http://nbviewer.ipython.org/urls/raw.github.com/pymc-devs/pymc/glm/pymc/examples/GLM.ipynb

**Comment by fonnesbeck** [comment]
Not directly related to this pull request, but it seems odd that a very simple model (the hierarchical GLM) with a modest number of observations takes so long to run under the NUTS sampler. The second model takes almost 5 minutes to run just 2K iterations with NUTS on my machine; switching to a slice sampler takes just 3 seconds!

**Comment by fonnesbeck** [comment]
I think this is pretty cool. The one thing that I still think will be confusing is that `glm` returns starting values rather than variables. While this is a convenience, it is a little inconsistent with how the model building interface works elsewhere, where functions that create variables return those variables and we call `find_MAP` manually to get at the starting values. Will this not be an issue in the case where the glm is just a component of a larger model?

**Comment by jsalvatier** [comment]
@fonnesbeck I think that's related to poor tuning of the covariance matrix? I'm not surprised it takes a little longer for small models, but it should be able to do better than that. I have some tuning related ideas, but I have to get them to work better. We definitely have to tackle that problem.

**Comment by twiecki** [comment]
@fonnesbeck I agree that it's weird it's returning the starting point. How about this then: instead it sets the `test_value` on the nodes and returns a list of all random variables.

The sampling with NUTS is indeed quite a bit slower (but slice has a hard time on the later models, at least when I tried). Initialization is the tricky part here and actually adds quite some complexity to the code (such as the `statsmodels` dependency).

**Comment by jsalvatier** [comment]
Setting `test_value` very much seems a bit hacky to me, but I do think this is a problem that we should figure out how to deal with. Try brainstorming some possible solutions before looking at my brainstorm.

Brainstorming about it: 
1. Maybe it is the right solution
2. Models could have a list of 'possible starting points'
3. We could have a second function for finding an appropriate starting point. 
4. We could have an automatic starting point finder a little like a step method assignment function.

**Comment by twiecki** [comment]
@jsalvatier From a pure usage stand-point I think 3. integrates best with the syntax of the rest of pymc3. Like this?

``` python
vars = glm('y ~ x', data)
start = find_glm_starting_point(vars=vars)
```

The problem with this however is that the random vars do not contain all the information necessary to initialize (missing are the linear model string and the link function). We could introduce a new GLM object that gets returned instead which contains the vars, model descriptor, link function etc. E.g.:

``` python
glm_obj = GLM('y ~ x', data)
start = glm_obj.find_starting_point()
```

**Comment by jsalvatier** [comment]
Hmm, I'm not sure what to do. Is there something we can do that's good enough for now so we can integrate this and fix in the future? Maybe your original idea is a good way to do that. 

You can just pass `testval` to each of the random variables.

**Comment by twiecki** [comment]
@fonnesbeck @jsalvatier OK, instead of returning a starting point `glm.glm` now sets the test_values of the vars (and returns them). A nice side-effect is that it makes the syntax even more concise which is reassuring, e.g.:

``` python
with Model() as model:
    glm.glm('y ~ x', data)
    trace = sample(2000, Slice())
```

is all that's required for the simplest model.

You can view the NB with the updated syntax here:
http://nbviewer.ipython.org/urls/raw.github.com/pymc-devs/pymc/glm/pymc/examples/GLM.ipynb

P.S. still needs unittests and better documentation, but if we agree on the syntax I can start with that.

**Comment by fonnesbeck** [comment]
I think this looks great.

Yes, documentation. Writing all this PyMC 3 documentation is beginning to scare me, but it needs to be done.

**Comment by twiecki** [comment]
OK, I added some docs and unittests. Should be good to merge.

The travis failure is unrelated to the glm stuff:

``` ======================================================================
ERROR: pymc.tests.test_examples.test_examples('/home/travis/build/pymc-devs/pymc/pymc/examples/dirichlet.py',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pymc-devs/pymc/pymc/tests/test_examples.py", line 37, in check_example
    imp.load_source('__main__', path.basename(p))
  File "dirichlet.py", line 17, in <module>
    H = model.d2logpc()
  File "/home/travis/build/pymc-devs/pymc/pymc/model.py", line 84, in d2logpc
    return compilef(hessian(model.logp, vars))
  File "/home/travis/build/pymc-devs/pymc/pymc/memoize.py", line 14, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/home/travis/build/pymc-devs/pymc/pymc/theanof.py", line 89, in hessian
    return -jacobian(gradient(f, vars), vars)
  File "/home/travis/build/pymc-devs/pymc/pymc/memoize.py", line 14, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/home/travis/build/pymc-devs/pymc/pymc/theanof.py", line 84, in jacobian
    return t.concatenate([jacobian1(f, v) for v in vars], axis=1)
  File "/home/travis/build/pymc-devs/pymc/pymc/theanof.py", line 76, in jacobian1
    return theano.map(grad_i, idx)[0]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/scan_module/scan_views.py", line 68, in map
    name=name)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/scan_module/scan.py", line 732, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "/home/travis/build/pymc-devs/pymc/pymc/theanof.py", line 74, in grad_i
    return gradient1(f[i], v)
  File "/home/travis/build/pymc-devs/pymc/pymc/theanof.py", line 57, in gradient1
    return t.flatten(t.grad(f, v, disconnected_inputs='warn'))
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 528, in grad
    grad_dict, wrt, cost_name)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1101, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 913, in access_term_cache
    node.outputs, new_output_grads):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/op.py", line 725, in get_debug_values
    rval.append(get_test_value(arg))
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/op.py", line 641, in get_test_value
    v_tensor = theano.tensor.as_tensor_variable(v)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/tensor/basic.py", line 217, in as_tensor_variable
    raise AsTensorError("Cannot convert %s to TensorType" % str_x, type(x))
AsTensorError: ('Cannot convert [Split{2}.0, Split{2}.1] to TensorType', <type 'list'>)
```

**Comment by fonnesbeck** [comment]
Passes all tests on my machine.

**Comment by fonnesbeck** [comment]
Travis still gives the error above, though I cannot replicate it locally. Both are using theano 0.6.0rc3.

**Comment by twiecki** [comment]
I opened up a separate issue here https://github.com/pymc-devs/pymc/issues/317

**Comment by aflaxman** [comment]
I'm installing PyMC on a fresh Anaconda distribution of Python 2.7, and it fails with an error about Patsy:

```
In [1]: import pymc
Warning: statsmodels not found, only importing parts of glm.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5f262cfcb99b> in <module>()
----> 1 import pymc

/snfs2/HOME/abie/pymc/pymc/__init__.py in <module>()
     18 from .tests import test
     19
---> 20 import glm

/snfs2/HOME/abie/pymc/pymc/glm/__init__.py in <module>()
      6 except ImportError:
      7     print "Warning: statsmodels not found, only importing parts of glm."
----> 8     from .glm import linear_component

/snfs2/HOME/abie/pymc/pymc/glm/glm.py in <module>()
      2 import numpy as np
      3 from pymc import  *
----> 4 import patsy
      5 import theano
      6 import pandas as pd

ImportError: No module named patsy
```

Can this dependency be added to the `setup.py install` process automatically somehow?

Related, after I've installed Patsy, I get similar complaints about statsmodels:

```
In [1]: import pymc
Warning: statsmodels not found, only importing parts of glm.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5f262cfcb99b> in <module>()
----> 1 import pymc

/snfs2/HOME/abie/pymc/pymc/__init__.pyc in <module>()
     18 from .tests import test
     19
---> 20 import glm

/snfs2/HOME/abie/pymc/pymc/glm/__init__.py in <module>()
      6 except ImportError:
      7     print "Warning: statsmodels not found, only importing parts of glm."
----> 8     from .glm import linear_component

/snfs2/HOME/abie/pymc/pymc/glm/glm.py in <module>()
      6 import pandas as pd
      7 from collections import defaultdict
----> 8 from statsmodels.formula.api import glm as glm_sm
      9 import statsmodels.api as sm
     10 from pandas.tools.plotting import scatter_matrix

ImportError: No module named formula.api
```

With `conda install patsy statsmodels` everything works, so this is no big deal, just some information that could help make pymc3 easier to get started with.

I can make this into a separate issue if that would be helpful.

**Comment by jsalvatier** [comment]
Thanks for the report, we definitely should fix this. Please do make a new issue.

**Comment by twiecki** [comment]
Thanks @aflaxman. Please open a separate issue for this.

**Comment by aflaxman** [comment]
Done is #382

**Comment by nikisix** [comment]
it's possible I'm simply confused, but when I try getting the quadratic regressor using the glm-submodule via:
glm.glm('y ~ x + x**2', data)

trace.varnames only has
['Intercept', 'x', 'sd_log', 'sd']

I was expecting some sort of x**2 coef term in there. Am I thinking about this wrong, or should there be something else in there?

x-post from: https://disqus.com/home/discussion/databozo/exploring_pymc3_databozo_02/?utm_source=reply&utm_medium=email&utm_content=read_more#comment-2432325913

**Comment by twiecki** [comment]
Have you tried x^2?

**Comment by jonsedar** [comment]
@nikisix you probably want glm.glm('y ~ x + np.power(x, 2)', data)"

Patsy wants the explicit numpy function, passed as a string

**Comment by twiecki** [comment]
Seems like Jon is right: http://stackoverflow.com/questions/31978948/python-stats-models-quadratic-term-in-regression

**Comment by jonsedar** [comment]
I only know because yesterday afternoon I tried doing the exact same thing, ha :)

**Comment by nikisix** [comment]
@jonsedar great stuff!

**Pull request merged**
