### PR TITLE
Added vagrant scripts for conda build and upload

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Conda package here: https://binstar.org/kyleabeauchamp/pymc

```
conda install -c https://conda.binstar.org/kyleabeauchamp pymc
```

**Comment by fonnesbeck** [comment]
This works using miniconda and Python 3.4.

**Comment by kyleabeauchamp** [comment]
Wait, I didn't actually upload a 3.4 package.  Did you just build one?

**Comment by kyleabeauchamp** [comment]
E.g. I just have 2.7:

https://binstar.org/kyleabeauchamp/pymc/files

**Comment by fonnesbeck** [comment]
I just built one, which had been failing previously.

**Comment by fonnesbeck** [comment]
Works here for 2.7 also. Can I merge this once it passes, or is there more you want to do? I will also re-tag the release once it is merged.

**Comment by kyleabeauchamp** [comment]
I think this is good enough for now.

**Comment by kyleabeauchamp** [comment]
Actually, I don't fully understand how to handle the MD5 changing upon the re-tagged release--it's a chicken and egg problem.  But we can adjust that manually for nwo.

**Pull request merged**
