### PR TITLE
Making PyMC 2.3 run on Python 3.3

### PR DESCRIPTION
**Pull request by terhardt**
I made some changes to PyMC to make it compile and run on Python 3.3.
Please review these before merging, because this is my first contact with Python 3.3. 

I can also squash the commits down, if you prefer.

Sorry, but it looks like I accidentally "fixed" some trailing white spaces in the files that I touched.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Are you able to build this on Anaconda? I get a `UnicodeDecodeError` when building the Fortran extensions.

**Comment by terhardt** [comment]
Yes I am. I got that error as well but adding the utf-8 tag to the setup.py in https://github.com/tobeplugged/pymc/commit/8d4d35db9077982d2ec8e6609b570169ed484666 fixed that.

But than again I ran the build manually without conda build. Because that just pulls the latest `tar.gz` from pypi

**Comment by fonnesbeck** [comment]
Hmm. I was testing your pull request, so its in there but I am still getting that error.

**Comment by terhardt** [comment]
I think the problem is, that the conda recipe is getting the source from pypi rather than from the current directory. I have not found a way to make `conda build conda` actually build the current state of the repo.

**Comment by terhardt** [comment]
What I did is initialize a conda environment with python 3 (numpy, scipy, matplotlib and pytables) and ran `python setup.py build_ext --inplace` to build and than ran the test suite.

This is just what conda build would do (except installing matplotlib and pytables, which conda build installs for testing purposes).

**Comment by fonnesbeck** [comment]
OK, merged. Might need todo a 2.3.3 release, but will wait a bit.

**Comment by terhardt** [comment]
Okay, thanks. I've found something else in the tests where `Matplot` is imported but not used which makes the tests fail if matplotlib is not installed. I will look into that later this week.

**Pull request merged**
