### PR TITLE
Correct docs for Bernoulli, Poisson, Negative Binomial, Geometric  and HyperGeometric

### PR DESCRIPTION
**Pull request by SangamSwadiK**
**What is this PR about?**
Issue: #5459 
This PR corrects docs for Bernoulli, Poisson, Negative Binomial, Geometric  and missing plot context in HyperGeometric for numpydoc compliance.

**Checklist**
+ [ ] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [ ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
None

## Bugfixes / New features
None

## Docs / Maintenance
Corrects docs of the mentioned discrete distributions for numpydoc compliance.
#DataUmbrellaPyMCSprint2022 @reshamas

### CODE REVIEW

**Review by michaelosthege — COMMENTED** [review]
@OriolAbril can you review here? I think there need to be additional spaces left of the `:`?

For example `mu : tensor_like of float` instead of `mu: tensor_like of float`

**Comment by SangamSwadiK** [comment]
> @OriolAbril can you review here? I think there need to be additional spaces left of the `:`?
> 
> For example `mu : tensor_like of float` instead of `mu: tensor_like of float`

Hi, I looked into the guide on [dataumbrella ](https://pymc-data-umbrella.xyz/en/latest/sprint/tutorials/docstring_tutorial.html)
and updated with correct spacing before and after colon.

**Comment by cluhmann** [comment]
You might want to include `:context: close-figs` just after the `.. plot::` as detailed in [the tutorial](https://pymc-data-umbrella.xyz/en/latest/sprint/tutorials/docstring_tutorial.html#section-independent-comments).  Otherwise, it looks good to me.

**Comment by twiecki** [comment]
Ping @SangamSwadiK , do you know what needs to be done here?

**Comment by SangamSwadiK** [comment]
> Ping @SangamSwadiK , do you know what needs to be done here?

@cluhmann @twiecki 
Hi, sorry for the late reply, was in middle of heavy monsoon and a storm.

I've gone through the tutorial and have already added the `:context: close-figs` in the previous PR, and I've checked again. I may be missing something, please let me know if I missed something.

Thanks for helping !!

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @SangamSwadiK!

**Pull request merged**
