### PR TITLE
Gradient branch

### PR DESCRIPTION
**Pull request by jsalvatier**
adds gradient calculation interface as well as better syntax for deterministic creation and many numpy-like deterministic factory functions.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
There seems to only be two small comment changes in the pull request.

**Comment by jsalvatier** [comment]
There is some issue that I caused by accidentally committing to the master branch and then undoing those changes, so that it thinks the master is fully up to date. My Git foo is not strong enough to know how to fix this. If you look at the actual source, you'll see that there are a lot of changes. Do you have any advice on how to proceed?

**Comment by fonnesbeck** [comment]
Let me have a look. Are all the same changes on gradientBranch? If so, it may be easier just to merge branches, rather than do a pull merge.

**Comment by jsalvatier** [comment]
"all the same"? All the important changes are on gradientBranch if that's what you're asking.

**Comment by fonnesbeck** [comment]
Looks like your git foo is strong -- you already merged the changes in commit  a4b72f7507a9c68ad783 so there is nothing for me to do, apart from merge these two minor changes! I assume you can do that yourself ...

Looking forward to testing this. Will be a nice addition to the 2.2 release.

**Comment by jsalvatier** [comment]
That was a mistake on my part, I tried to undo them in b36cc9fa4694dd8e294d. If you're OK with me merging them myself, I can do that (reopened because I'm not sure you'll get the comment otherwise).

**Comment by fonnesbeck** [comment]
Yeah, go for it. The beauty of git is that we can always undo something nasty if we need to.

**Pull request closed without merging**
