### PR TITLE
Faster distribution tests + other test fixes

### PR DESCRIPTION
**Pull request by jsalvatier**
Tried to fix long test issues causing Travis timeouts and a variety of other test issues.
Rebased version of https://github.com/pymc-devs/pymc/pull/263

### CODE REVIEW

**Comment by fonnesbeck** [comment]
I get two errors in `test_distributions` with this branch, including the one for `test_beta` cited previously:

```
======================================================================
FAIL: pymc.tests.test_distributions.test_discrete_unif
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose-1.2.1-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/fonnescj/Code/pymc3/pymc/tests/knownfailure.py", line 13, in inner
    raise AssertionError('Failure expected: ' + msg)
AssertionError: Failure expected: int32 in Rdunif causes this to fail but not int64

======================================================================
FAIL: pymc.tests.test_distributions.test_beta
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose-1.2.1-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/fonnescj/Code/pymc3/pymc/tests/test_distributions.py", line 49, in test_beta
    checkd(Beta, Unit, {'alpha': Rplus * 5, 'beta': Rplus * 5})
  File "/Users/fonnescj/Code/pymc3/pymc/tests/test_distributions.py", line 141, in checkd
    check_dlogp(m, value, domains)
  File "/Users/fonnescj/Code/pymc3/pymc/tests/test_distributions.py", line 189, in check_dlogp
    decimal=6, err_msg=str(pt))
  File "/Library/Python/2.7/site-packages/numpy-1.8.0.dev_3084618_20130514-py2.7-macosx-10.8-intel.egg/numpy/testing/utils.py", line 457, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/Library/Python/2.7/site-packages/numpy-1.8.0.dev_3084618_20130514-py2.7-macosx-10.8-intel.egg/numpy/testing/utils.py", line 818, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/Library/Python/2.7/site-packages/numpy-1.8.0.dev_3084618_20130514-py2.7-macosx-10.8-intel.egg/numpy/testing/utils.py", line 651, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals
[  5.00000000e+02   5.00000000e-02   1.00000000e-03]
(mismatch 33.3333333333%)
 x: array([ -6.90765518e+00,   2.67105524e+01,   4.99000951e+05])
 y: array([ -6.90765518e+00,   2.67105524e+01,   4.99000951e+05])

----------------------------------------------------------------------
```

**Comment by jsalvatier** [comment]
I still can't for the life of me replicate these errors, even after re-installing all the relevant packages. Could you look at them @fonnesbeck?

**Comment by fonnesbeck** [comment]
Very odd. The errors above were from Travis, and not my local machine. Did you install using `develop`? I will see what I can find.

**Comment by jsalvatier** [comment]
Hmm, yeah, I'll try without develop when I get a chance. Thanks for taking a look.

**Comment by fonnesbeck** [comment]
A little progress here: that known failure does not fail anymore -- I tested it with both int32 and int64 with no problems. The `test_beta` error seems to be related to some imprecision in the log-likelihood with small values of alpha or beta (e.g. 0.01); it is only accurate to 5 digits rather than 7. I can only guess that this comes from `gammln`, but who knows. So, running the test with `Rplusbig` allows it to pass. I will change this for now, and open an issue to look at it more closely later.

**Comment by fonnesbeck** [comment]
Unfortunately, the tests still time out on Travis (at least on the tests run when this branch was merged).

**Comment by jsalvatier** [comment]
Looks like they're timing out on the examples now! Have we made significant changes there? They were running in about 30 minutes before.

**Comment by fonnesbeck** [comment]
Not that I can tell. There have been no meaningful changes to the examples in almost 2 weeks.

**Pull request merged**
