### PR TITLE
Minor test fixes

### PR DESCRIPTION
**Pull request by jsalvatier**
Test fixes and better error message too

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Well, the examples ran in just under 10 min on my MacBook just now.

**Comment by jsalvatier** [comment]
Finally! Its great to finally having passing tests ...

**Comment by fonnesbeck** [comment]
Awesome. Passed on Travis as well. Nicely done.

**Comment by jsalvatier** [comment]
Phew, now lets try never to merge non-passing code to the effective master.

**Pull request merged**
