### PR TITLE
New Plots

### PR DESCRIPTION
**Pull request by fonnesbeck**
Added `forestplot` and `autocorrplot`

### CODE REVIEW

**Comment by twiecki** [comment]
Is there a fallback to single-threaded?

I have to say though, having extra code just to circumvent travis feels wrong.

```
======================================================================
ERROR: pymc.tests.test_diagnostics.test_gelman_rubin
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pymc-devs/pymc/pymc/tests/test_diagnostics.py", line 10, in test_gelman_rubin
    ptrace = psample(n, [dm.step1, dm.step2], dm.start, threads=2)
  File "/home/travis/build/pymc-devs/pymc/pymc/sample.py", line 91, in psample
    p = mp.Pool(threads)
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 115, in __init__
    self._setup_queues()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 210, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied

======================================================================
ERROR: pymc.tests.test_plots.test_forest_plot
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pymc-devs/pymc/pymc/tests/test_plots.py", line 16, in test_forest_plot
    ptrace = psample(1000, [dm.step1, dm.step2], dm.start, threads=2)
  File "/home/travis/build/pymc-devs/pymc/pymc/sample.py", line 91, in psample
    p = mp.Pool(threads)
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 115, in __init__
    self._setup_queues()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 210, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
```

**Comment by twiecki** [comment]
It does seem as if they want to support this though:
https://github.com/travis-ci/travis-core/issues/187

**Comment by jsalvatier** [comment]
I think actually it would be great to have, automatic switching to single threading. This will be a problem on other computers too. Didn't you run into this @twiecki ?

**Comment by fonnesbeck** [comment]
Can we not just put all the tests involving `psample` in a test suite that does not get called by Travis? That's where it will come up, correct?

**Comment by jsalvatier** [comment]
I think that's a good quick fix, but I think there are probably other places too.

**Comment by twiecki** [comment]
I think I fixed the restriction of not being able to run parallel on pymc3 with b73c43b00c585a48c7468f831b5fbdda2bd88465

Re your question @jsalvatier: Not sure we need a fall-back for users. The reason I fixed it was to make it run on travis back then.

**Comment by fonnesbeck** [comment]
Are we happy with these plots? Not sure if we want to add the acf plot to traceplot as we did for PyMC 2. I'm leaning against it, but could live with it either way.

**Comment by jsalvatier** [comment]
Looks good to me. Assuming you've run the tests on your machine, go ahead and merge. 

I'm ok with ACF in or out too.

**Pull request merged**
