### PR TITLE
Faster distribution tests + other test fixes

### PR DESCRIPTION
**Pull request by jsalvatier**
Tried to fix long test issues causing Travis timeouts and a variety of other test issues.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
I'm getting Theano.gof errors a la:

```
    ERROR (theano.gof.opt): Optimization failure due to: local_setsubtensor_of_allocs
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/theano/gof/opt.py", line 1206, in process_node
    replacements = lopt.transform(node)
  File "/Library/Python/2.7/site-packages/theano/tensor/opt.py", line 2112, in local_setsubtensor_of_allocs
    replace_y = get_scalar_constant_value(y)
  File "/Library/Python/2.7/site-packages/theano/tensor/basic.py", line 613, in get_scalar_constant_value
    ret = get_scalar_constant_value(ret)
  File "/Library/Python/2.7/site-packages/theano/tensor/basic.py", line 612, in get_scalar_constant_value
    ret = v.owner.inputs[0].owner.inputs[v.owner.op.idx_list[0]]
TypeError: list indices must be integers, not Scalar
```

**Comment by fonnesbeck** [comment]
I'm curious why the `bound` function used in the distributions in some cases bounds values as well as parameters (e.g. gamma) but just parameters in others (e.g. Bernoulli).

**Comment by jsalvatier** [comment]
That is an optimization error on theano's part that it recovers from and so
does not cause the tests to fail. I have a ticket open: https://github.com/Theano/Theano/issues/1288.

The `bound` function takes a log probability as first arg and then a varargs
of boolean tensors. If any of the boolean tensors are not true, then
`bound` returns -inf otherwise it returns the log probablility.
https://github.com/pymc-devs/pymc/blob/pymc3/pymc/distributions/dist_math.py Is
there a way we can make that more obvious?

**Comment by fonnesbeck** [comment]
The beta distribution test seems to fail consistently now. I was not getting this before:

```
Arrays are not almost equal to 6 decimals
[  5.00000000e+02   5.00000000e-02   1.00000000e-03]
(mismatch 33.3333333333%)
 x: array([ -6.90765518e+00,   2.67105524e+01,   4.99000951e+05])
 y: array([ -6.90765518e+00,   2.67105524e+01,   4.99000951e+05])
```

**Comment by jsalvatier** [comment]
I think that might be the fix to the derivative check. It wasn't working properly before.  However, I don't get that error on mine.

**Comment by jsalvatier** [comment]
I think the test failure must be due to using psample, which I guess travis does not like.

**Comment by jsalvatier** [comment]
Weird, I am not able to reproduce these issues even with new the git versions of theano and numpy.

**Comment by fonnesbeck** [comment]
The failure above [occurred again](https://s3.amazonaws.com/archive.travis-ci.org/jobs/7272002/log.txt) on Travis yesterday.

**Pull request closed without merging**
