### PR TITLE
Using standard imports in the tutorial notebook

### PR DESCRIPTION
**Pull request by zonca**
using `import pymc as pm`, see issue #367

### CODE REVIEW

**Comment by twiecki** [comment]
What about the other examples (e.g. banana.py)? Ideally those would be changed as well.

**Comment by zonca** [comment]
Sure, I would like to modify all of them, however I noticed a lot of them are failing, do you still need to upgrade them to pymc3?

**Comment by twiecki** [comment]
Shouldn't be failing. Which ones specifically? (One mistake I always make is to not clean the branch when switching properly).

**Comment by zonca** [comment]
It looks like also Travis fails:
https://travis-ci.org/pymc-devs/pymc/jobs/12792507

Shouldn't be failing. Which ones specifically? (One mistake I always make
is to not clean the branch when switching properly).

—
Reply to this email directly or view it on
GitHubhttps://github.com/pymc-devs/pymc/pull/369#issuecomment-27180832
.

**Comment by twiecki** [comment]
Travis is a little finicky sometimes (I restarted now). The tests pass locally for me though.

**Comment by zonca** [comment]
I'll work on the examples in the next couple of weeks, I suggest to start merging this.

**Comment by twiecki** [comment]
Sure, why not.

**Comment by twiecki** [comment]
Thanks!

**Pull request merged**
