### PR TITLE
MAP was crashing for me, this fixes it

### PR DESCRIPTION
**Pull request by aflaxman**
I was fitting a part of my model with no data to get good initial values, and it was crashing with the repo PyMC.  This commit fixes the crash, and hopefully gives sensible values as well.  (And oops, the pump example was not supposed to be part of this... I've got some git to learn.)

### CODE REVIEW

**Comment by apatil** [comment]
Thanks, Abie, looks good. Do you want the pump example in there, as long as it's there now?

**Comment by aflaxman** [comment]
I'm confused about how pull requests work, but there is a bug fix in this commit:
    https://github.com/aflaxman/pymc/commit/fa78c3f960d8e8c1a34008b0af36bbdce6f73911

**Comment by apatil** [comment]
If I accept the pull request, all of the commits showing on this page will get merged into the master branch. If you want the pump example out of there, the thing to do is delete it using git rm, then commit and push the change to your pymc repository.

**Comment by fonnesbeck** [comment]
I did a selective merge in 7bb831940c9775823b17640139949a59c6569c67 and d5b386ac1b36d2fa082e2fc967a7719538026522

**Pull request closed without merging**
