### PR TITLE
Include autocorrelation of trace in Matplotlib.plot

### PR DESCRIPTION
**Pull request by aflaxman**
This commit makes the Matplotlib.plot function include an autocorrelation plot as well as the trace of the MCMC draws

This is often a more informative indicator of MCMC convergence.

This is my first pull request, so please let me know if you would like me to use a different mechanism for this contribution.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
I like it. The ACF should be symmetric either side of zero, right? So I wonder if only plotting one half of the mirror image might be better, in terms of resolution. Any other thoughts from anyone?

**Comment by fonnesbeck** [comment]
Abie,

This seems to choke on vector-valued nodes. I get a key error associated with the rows in the plot. Have you gotten this to work for any model?

**Comment by aflaxman** [comment]
It works for me for https://github.com/aflaxman/pymc-multilevel-example which has a node like this::

```
B = mc.Normal('B', mu=[0, 0], tau=10000**-1)
```

Is that the sort of thing you are having trouble with?

**Comment by fonnesbeck** [comment]
Try the pump.py example, and plot the Stochastic 'theta'. I get the following:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/Users/fonnescj/Python/<ipython-input-6-a960ee01939d> in <module>()
----> 1 Matplot.plot(M.theta)

/Users/fonnescj/Code/pymc/pymc/Matplot.pyc in wrapper(pymc_obj, *args, **kwargs)
    324                 data = pymc_obj.trace()[start:]  # This is deprecated. DH
    325                 name = pymc_obj.__name__
--> 326                 f(data, name, *args, **kwargs)
    327             return
    328         except AttributeError:

/Users/fonnescj/Code/pymc/pymc/Matplot.pyc in plot(data, name, format, suffix, path, common_scale, datarange, new, last, rows, num, fontmap, verbose)
    420             _last = not (_num + 1) % (_rows * 2) or (i==len(tdata)-1)
    421 
--> 422             plot(tdata[i], name+'_'+str(i), format=format, path=path, common_scale=common_scale, datarange=datarange, suffix=suffix, new=_new, last=_last, rows=_rows, num=_num)
    423 
    424 

/Users/fonnescj/Code/pymc/pymc/Matplot.pyc in wrapper(pymc_obj, *args, **kwargs)
    340             return
    341         # If others fail, assume that raw data is passed

--> 342         f(pymc_obj, *args, **kwargs)
    343 
    344     wrapper.__doc__ = f.__doc__

/Users/fonnescj/Code/pymc/pymc/Matplot.pyc in plot(data, name, format, suffix, path, common_scale, datarange, new, last, rows, num, fontmap, verbose)
    386 
    387         # Call trace

--> 388         trace(data, name, datarange=datarange, rows=rows*2, columns=2, num=num, last=last, fontmap=fontmap)
    389         # Call autocorrelation

    390         autocorrelation(data, name, rows=rows*2, columns=2, num=num+2*rows, last=last, fontmap=fontmap)

/Users/fonnescj/Code/pymc/pymc/Matplot.pyc in wrapper(pymc_obj, *args, **kwargs)
    340             return
    341         # If others fail, assume that raw data is passed

--> 342         f(pymc_obj, *args, **kwargs)
    343 
    344     wrapper.__doc__ = f.__doc__

/Users/fonnescj/Code/pymc/pymc/Matplot.pyc in trace(data, name, format, datarange, suffix, path, rows, columns, num, last, fontmap, verbose)
    498     # Smaller tick labels

    499     tlabels = gca().get_xticklabels()
--> 500     setp(tlabels, 'fontsize', fontmap[rows])
    501 
    502     tlabels = gca().get_yticklabels()

KeyError: 8
```

**Comment by fonnesbeck** [comment]
It appears to occur for nodes that require multiple pages of plots (i.e. 4 or more).

**Comment by fonnesbeck** [comment]
I fixed this, and tweaked the plot slightly to put all the plots for a particular node together, rather than grouping them by type of plot. I think it makes it easier to evaluate a particular node when there are multiple on one figure. Have a look on the new_plots branch (7258e3023cf3cd267163e31c17085bf892b399c7).

**Comment by aflaxman** [comment]
Looks good, thanks.  I couldn't find the pump.py example in the pymc examples folder, but I did find one in the mailing list archives, so I added that to my fork of the repo, in case it's helpful.

**Comment by fonnesbeck** [comment]
It's not in the example set that ships with pymc, but it's on the wiki.

**Comment by aflaxman** [comment]
Ah, I see. For anyone looking for this in the future, a direct link to the pump.py example is here: https://github.com/pymc-devs/pymc/wiki/Pump

**Comment by fonnesbeck** [comment]
OK, will merge from new_plots branch.

**Pull request closed without merging**
